name: Generate Test Report Table

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"  # 4pm UTC = 8am PST / 9am PDT, 7 hours after testapps run

env:
  GITHUB_TOKEN: ${{ github.token }}
  numDays: 7
  numDaysExtended: 30

jobs:
  generate-report:
    runs-on: ubuntu-20.04
    steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Desktop SDK prerequisites
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 15
        max_attempts: 3
        command: |
          python3 scripts/gha/install_prereqs_desktop.py --gha_build
          python3 -m pip install requests python-dateutil progress attrs
    - name: Fetch GitHub jobs
      run: |
        python3 scripts/gha/report_build_status.py --token ${{ github.token }} --days ${{ env.numDays }} --write_cache build_status_short.cache
        python3 scripts/gha/report_build_status.py --token ${{ github.token }} --days ${{ env.numDaysExtended }} --write_cache build_status.cache
    - name: Generate report files
      run: |
        python3 scripts/gha/report_build_status.py --token ${{ github.token }} --days ${{ env.numDays }} --output_markdown --read_cache build_status_short.cache > report_short.md
        python3 scripts/gha/report_build_status.py --token ${{ github.token }} --days ${{ env.numDaysExtended }} --output_markdown --read_cache build_status.cache > report_extended.md
        python3 scripts/gha/report_build_status.py --token ${{ github.token }} --days ${{ env.numDays }} --read_cache build_status_short.cache > report.txt
    - name: Generate comment string
      run: |
        echo -n > comment.md
        cat >> comment.md <<EOF
        ***

        EOF
        cat report_short.md >> comment.md
        cat >> comment.md <<EOF

        <details><summary>View extended history</summary>
	EOF
        cat report_extended.md >> comment.md
        cat >> comment.md <<EOF
        </details>
        <details><summary>📄</summary><pre>
        EOF
        cat report.txt >> comment.md
        cat >> comment.md <<EOF
        </pre></details>
        EOF
    - name: Show comment string
      run: |
        cat comment.md
    - name: Upload comment file artifact
      uses: actions/upload-artifact@v3
      with:
        name: comment.md
        path: comment.md
    - name: Upload build status cache (debugging)
      uses: actions/upload-artifact@v3
      with:
        name: build_status.cache
        path: build_status.cache
